bases:
- ../../base
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bubbles-app
    path: deployment.yaml
  - target:
      version: v1
      group: route.openshift.io
      kind: Route
      name: bubbles-app
    path: route.yaml
  - target:
      version: v1
      kind: Service
      name: bubbles-app
    path: service.yaml
resources:
- namespace.yaml
