bases:
- ../base
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bgd
    path: bgd-deployment.yaml
  - target:
      version: v1
      group: route.openshift.io
      kind: Route
      name: bgd
      namespace: bgd-staging
    path: bgd-route.yaml
resources:
- bgd-namespace.yaml
