apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: bubble-app
  name: bubble-app
  namespace: bubble-app
spec:
  host: "PATCH_ME"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: bubble-app
    weight: 100
