---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bubble-app
  name: bubble-app
  namespace: iae-staging
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bubble-app
